services:
  # Main application (direct host nginx proxy)
  proposal-share:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: proposal-share
    ports:
      - "3001:3001"  # Expose directly to host for nginx proxy
    environment:
      - NODE_ENV=production
      - ADMIN_KEY=${ADMIN_KEY:-rahasia-jangan-di-bagi}
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      # Persist SQLite database
      - proposal_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "const http = require('http'); http.request({hostname:'localhost',port:3001,path:'/'},(r)=>r.statusCode===200?process.exit(0):process.exit(1)).on('error',()=>process.exit(1)).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  proposal_data:
    driver: local
